### ISSUE TITLE
Failure opening old data

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#126]
On windows, but suspect more general. Tried opening DUI but didn't realise there was an existing data directory, and it crashed. This also happens trying to load this dui folder on linux. Have attached the erroneous file.

CCP4 7.0.76. Have never had a development version of DUI on this install, only the old release (_possibly_ an expert mode release).

```
C:\ccp4temp>dui


 TreeShow debug
 my_runner.step_list:

__________________________listing:
Traceback (most recent call last):
  File "C:\CCP4-7\7.0\Scripts\dui-script.py", line 12, in <module>
    load_entry_point('dui==2019.5', 'console_scripts', 'dui')()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\main_dui.py", line 96, in main
    ex = MainWidget()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\m_idials_gui.py", line 407, in __init__
    self.cli_tree_output(self.idials_runner)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\cli_utils.py", line 656, in __call__
    print_list(my_runner.step_list, my_runner.current_line)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\cli_utils.py", line 624, in print_list
    + str(uni.ll_command_lst[0])
AttributeError: 'CommandNode' object has no attribute 'll_command_lst'
```

[dui_files.zip](https://github.com/ccp4/DUI/files/3516448/dui_files.zip)

**Comment by dagewa** [comment]
I don't think DUI should guarantee opening old data, but it should not crash.
