### ISSUE TITLE
DUI fails to open (some nexus) images on Windows

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#128]
Trying to import the dataset provided by David Lawson; `dials.import` appears to run as the datablock.json is correctly written, but then DUI throws this exception whilst importing and then hangs:
```
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5D.c line 375 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5S.c line 865 in H5Sget_simple_extent_ndims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\outputs_n_viewers\img_viewer.py", line 1431, in img_changed_by_user
    self.set_img()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\outputs_n_viewers\img_viewer.py", line 1252, in set_img
    n_of_panels = len(self.my_sweep.get_raw_data(img_pos))
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\FormatMultiImage.py", line 24, in read
    return format_instance.get_raw_data(index)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\FormatNexus.py", line 133, in get_raw_data
    return self._raw_data[index]
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\nexus.py", line 1602, in __getitem__
    (slice(i, i + 1, 1), slice(0, height, 1), slice(0, width, 1)),
RuntimeError: dxtbx Internal Error: C:\msys64\home\W1J5\devtools\checkout\cctbx-phaser\cctbx_project\dxtbx\format\boost_python\nexus_ext.cc(39): DXTBX_ASSERT(rank == ndims) failure.
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5D.c line 375 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5S.c line 865 in H5Sget_simple_extent_ndims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\outputs_n_viewers\img_viewer.py", line 1423, in stack_changed_by_user
    self.set_img()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\outputs_n_viewers\img_viewer.py", line 1252, in set_img
    n_of_panels = len(self.my_sweep.get_raw_data(img_pos))
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\FormatMultiImage.py", line 24, in read
    return format_instance.get_raw_data(index)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\FormatNexus.py", line 133, in get_raw_data
    return self._raw_data[index]
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\nexus.py", line 1602, in __getitem__
    (slice(i, i + 1, 1), slice(0, height, 1), slice(0, width, 1)),
RuntimeError: dxtbx Internal Error: C:\msys64\home\W1J5\devtools\checkout\cctbx-phaser\cctbx_project\dxtbx\format\boost_python\nexus_ext.cc(39): DXTBX_ASSERT(rank == ndims) failure.
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5D.c line 375 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5S.c line 865 in H5Sget_simple_extent_ndims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5D.c line 375 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:/msys64/home/W1J5/devtools/checkout/hdf5-1.10.0-patch1/src/H5S.c line 865 in H5Sget_simple_extent_ndims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\m_idials_gui.py", line 699, in update_after_finished
    update_info(self)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\gui_utils.py", line 360, in update_info
    main_obj.img_view.ini_datablock(main_obj.cur_json)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\outputs_n_viewers\img_viewer.py", line 1094, in ini_datablock
    self.set_img()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dui\outputs_n_viewers\img_viewer.py", line 1252, in set_img
    n_of_panels = len(self.my_sweep.get_raw_data(img_pos))
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\FormatMultiImage.py", line 24, in read
    return format_instance.get_raw_data(index)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\FormatNexus.py", line 133, in get_raw_data
    return self._raw_data[index]
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\format\nexus.py", line 1602, in __getitem__
    (slice(i, i + 1, 1), slice(0, height, 1), slice(0, width, 1)),
RuntimeError: dxtbx Internal Error: C:\msys64\home\W1J5\devtools\checkout\cctbx-phaser\cctbx_project\dxtbx\format\boost_python\nexus_ext.cc(39): DXTBX_ASSERT(rank == ndims) failure.
```

**Comment by dagewa** [comment]
likely due to ongoing issues with HDF5 on CCP4 DIALS builds for Windows
