### ISSUE TITLE
dials failed: copy/paste

### ISSUE THREAD

**Issue by luisodls** [ccp4/DUI#28]
Detecting centroid outliers using the MCD algorithm
4096 reflections have been flagged as outliers

Summary statistics for 26268 observations matched to predictions:
------------------------------------------------------------------------
| | Min | Q1 | Med | Q3 | Max |
------------------------------------------------------------------------
| Xc - Xo (mm) | -0.2613 | -0.04677 | 0.001643 | 0.04439 | 0.2422 |
| Yc - Yo (mm) | -0.3084 | -0.05679 | 0.003756 | 0.06494 | 0.326 |
| Phic - Phio (deg) | -0.7391 | -0.1501 | 0.01417 | 0.1722 | 0.9084 |
| X weights | 283.5 | 392.4 | 400.7 | 404.4 | 405.6 |
| Y weights | 287.7 | 393 | 400.2 | 404.1 | 405.6 |
| Phi weights | 10.91 | 11.99 | 12 | 12 | 12 |
------------------------------------------------------------------------

Traceback (most recent call last):
File "/dls_sw/apps/dui/dials_w_miniconda/build/../modules/dials/command_line/refine.py", line 406, in <module>
halraiser(e)
File "/dls_sw/apps/dui/dials_w_miniconda/build/../modules/dials/command_line/refine.py", line 404, in <module>
script.run()
File "/dls_sw/apps/dui/dials_w_miniconda/build/../modules/dials/command_line/refine.py", line 255, in run
reflections, experiments)
File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/algorithms/refinement/refiner.py", line 466, in from_parameters_data_experiments
copy_experiments=copy_experiments)
File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/algorithms/refinement/refiner.py", line 538, in _build_components
cls.config_parameterisation(params, experiments, refman, do_stills, verbosity)
File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/algorithms/refinement/refiner.py", line 1312, in config_parameterisation
xl_ori_params, xl_uc_params)
File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/algorithms/refinement/refiner.py", line 1419, in config_restraints
if len(tie.sigmas) != 6:
TypeError: Please report this error to dials-support@lists.sourceforge.net: object of type 'NoneType' has no len()

**Comment by dagewa** [comment]
Something wrong with your phil file going into refinement. Do you mean to do unit cell restraints?

**Comment by dagewa** [comment]
@luisodls Any ideas what this was? If not, please close to keep the issue list tidy
