### ISSUE TITLE
another fail: copy/pasted from Jose B N

### ISSUE THREAD

**Issue by luisodls** [ccp4/DUI#29]
am testing it now from my desktop (ws072) on a dataset with 1500 images.
 

    it took 1min+ to load the image names for the chosen dataset (that’s bad).
    it’s taking minutes to find spots – is that normal? Took 2 minutes in the end.
    I like that the next step is the only button available
    the bravais table didn’t pop up first time round. The shell was prompting me to choose the lattice but I had to click on the history tree to eventually have the table popping up.
    I like the history tree.
    in the bravais lattice table, I got confused with cell parameters because some are in decimal, some (if number >100) are in scientific notation.
    The diffraction image does not show what image I’m looking at. Is it a raw image or is it an average? Or something else?
    The report view tab is great
    The report (and GUI in general) does not show there’s a problem. I only noticed because the log file turned red in the end. There’s an error that does not cause any visual feedback elsewhere.
    I used dataset /dls/labxchem/data/2017/lb16993-1/processing/beamline/lb16993-2/DM15/DM15-x0009/DM15-x0009_1_####.cbf
    Resolution rings in the image would be great.

 
Luis, I like it, it’s neat and compact. There are some snags, but looks very good already.
 
Cheers,
Jose’
 
Traceback (most recent call last):
  File "/dls_sw/apps/dui/dials_w_miniconda/build/../modules/dials/command_line/integrate.py", line 568, in <module>
    halraiser(e)
  File "/dls_sw/apps/dui/dials_w_miniconda/build/../modules/dials/command_line/integrate.py", line 566, in <module>
    script.run()
  File "/dls_sw/apps/dui/dials_w_miniconda/build/../modules/dials/command_line/integrate.py", line 325, in run
    reflections = integrator.integrate()
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/algorithms/integration/integrator.py", line 1150, in integrate
    self.reflections, _, time_info = processor.process()
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/algorithms/integration/processor.py", line 271, in process
    preserve_exception_message = True)
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/util/mp.py", line 171, in multi_node_parallel_map
    preserve_exception_message = preserve_exception_message)
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/util/mp.py", line 53, in parallel_map
    preserve_exception_message = preserve_exception_message)
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/easy_mp.py", line 623, in parallel_map
    result = res()
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 115, in __call__
    self.raise_handler( exception = exception )
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/scheduling/mainthread.py", line 100, in poll
    value = target( *args, **kwargs )
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/dials/util/mp.py", line 91, in __call__
    preserve_exception_message = self.preserve_exception_message)
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/easy_mp.py", line 623, in parallel_map
    result = res()
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 115, in __call__
    self.raise_handler( exception = exception )
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 145, in raise_with_stacktrace
    self.stacktrace( exception = exception )
  File "/dls_sw/apps/dui/dials_w_miniconda/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 86, in __call__
    raise exception
RuntimeError: Please report this error to dials-support@lists.sourceforge.net:
        There was a problem allocating memory for shoeboxes. Possible solutions
        include increasing the percentage of memory allowed for shoeboxes or
        decreasing the block size. This could also be caused by a highly mosaic
        crystal model - is your crystal really this mosaic?
          Total system memory: 6.26399 GB
          Limit shoebox memory: 4.69799 GB
          Required shoebox memory: 12.7337 GB

**Comment by dagewa** [comment]
@luisodls what is this issue? Can it be closed, or broken down into component problems?

**Comment by dagewa** [comment]
Lack of interaction here suggests it is not worth keeping this open.
